#!/usr/bin/env bash

set -e

CURRENT_DIR=$(pwd)
DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

is_stow_installed() {
  command -v stow >/dev/null 2>&1
}

install_stow() {
  echo "🔍 Detecting package manager..."

  if [[ "$OSTYPE" == "darwin"* ]]; then
    if command -v brew >/dev/null 2>&1; then
      echo "🍺 Installing stow via Homebrew..."
      brew install stow
      return
    fi
  elif command -v apt >/dev/null 2>&1; then
    echo "🧃 Installing stow via apt..."
    sudo apt update && sudo apt install -y stow
  elif command -v dnf >/dev/null 2>&1; then
    echo "🌶 Installing stow via dnf..."
    sudo dnf install -y stow
  elif command -v pacman >/dev/null 2>&1; then
    echo "🏹 Installing stow via pacman..."
    sudo pacman -Sy --noconfirm stow
  elif command -v zypper >/dev/null 2>&1; then
    echo "🧀 Installing stow via zypper..."
    sudo zypper install -y stow
  elif command -v apk >/dev/null 2>&1; then
    echo "🐋 Installing stow via apk..."
    sudo apk add stow
  elif command -v snap >/dev/null 2>&1; then
    echo "📦 Installing stow via snap..."
    sudo snap install stow
  else
    echo "❌ No supported package manager found. Please install GNU Stow manually."
    exit 1
  fi
}

main() {
  if is_stow_installed; then
    echo "✅ GNU Stow is already installed."
  else
    install_stow
    echo "✅ GNU Stow has been installed."
  fi

  if is_stow_installed; then
    echo "🔗 Symlinking files in $DOTFILES_DIR"
    echo "This will run the following command:"
    echo
    echo "> stow $DOTFILES_DIR --target=$HOME"
    stow "$DOTFILES_DIR" --target="$HOME"
    echo
    echo "✅ Done!"
  else
    echo "❌ GNU Stow is still not installed."
    exit 1
  fi

  exit 0
}

main
